import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { build } from "esbuild";
import { Miniflare, convertV4MiniflareOptions } from "miniflare";
import { defaultAlerts } from "../src/personal-alerts.js";
import { createECDH, randomBytes } from "node:crypto";

const bundle = await build({ entryPoints: [new URL("worker.js", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")], bundle: true, write: false, format: "esm", platform: "browser", target: "es2022" });
const messages = [];
let acceptEmail = true;
let pushStatus = 201;
const pushes = [];
let onDelivery = () => {};
const future = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10);
const feed = { checkedAt: new Date().toISOString(), courses: defaultAlerts.map(rule => ({ course: rule.course, collector: "golfnow" })), sourceChecks: defaultAlerts.map(rule => ({ course: rule.course, checkedAt: new Date().toISOString() })), teeTimes: [{ course: "Spring Creek Golf Club", date: future, time: "9:00 AM", allInPrice: 119, holes: 18, priceIsExact: true, availablePlayers: 4, availablePartySizes: [2, 4], rateName: "Public", url: "https://example.test/book" }] };
const createRuntime = (bindings = {}) => new Miniflare(convertV4MiniflareOptions({ workers: [{ modules: true, script: bundle.outputFiles[0].text, compatibilityDate: "2026-09-26", d1Databases: ["DB"], bindings: { ADMIN_SECRET: "test-admin", EMAIL_RELAY_SECRET: "test-relay", EMAIL_RELAY_URL: "https://mail.test/send", PUBLIC_EDITOR_EMAIL: "public@example.test", ...bindings }, outboundService: async request => {
  if (request.url.startsWith("https://mail.test/")) { const message = await request.json(); if (!acceptEmail) return Response.json({ ok: false }, { status: 503 }); messages.push(message); onDelivery(); return Response.json({ ok: true }); }
  if (request.url.startsWith("https://web.push.apple.com/")) { assert.equal(request.headers.get("Content-Encoding"), "aes128gcm"); assert.match(request.headers.get("Authorization"), /^vapid /); assert.equal((await request.arrayBuffer()).byteLength, 4096); if (pushStatus === 201) pushes.push(request.url); return new Response(null, { status: pushStatus }); }
  if (request.url.startsWith("https://fbp26.github.io/golfwithjim/api/")) return Response.json(feed);
  return new Response("Unexpected request", { status: 500 });
} }] }));
const runtime = createRuntime();

try {
  const database = await runtime.getD1Database("DB");
  const schema = await readFile(new URL("schema.sql", import.meta.url), "utf8");
  for (const statement of schema.split(";").map(value => value.trim()).filter(Boolean)) await database.prepare(statement).run();
  const admin = (path, body = {}) => runtime.dispatchFetch(`https://alerts.test/admin/${path}`, { method: "POST", headers: { Authorization: "Bearer test-admin", "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const enrollment = await admin("enroll", { email: "owner@example.test" });
  assert.equal(enrollment.status, 200);
  assert.equal((await enrollment.json()).welcomeDelivered, true);
  assert.equal(messages.length, 1);
  const token = messages[0].body.match(/#token=([a-f0-9]{64})/)[1];
  const preference = (method = "GET", body) => runtime.dispatchFetch("https://alerts.test/preferences", { method, headers: { Authorization: `Bearer ${token}`, Origin: "https://fbp26.github.io", "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const original = await (await preference()).json();
  assert.equal(original.rules.length, 2);
  assert.equal(original.email, "owner@example.test");
  assert.equal((await (await admin("check")).json()).sent, 1);
  assert.equal((await (await admin("check")).json()).sent, 0);
  assert.equal(messages.length, 2);
  assert.match(messages[1].body, /Spring Creek Golf Club/);
  assert.match(messages[1].body, /Magnolia Green Golf Club/);
  feed.teeTimes[0].allInPrice = 118;
  acceptEmail = false;
  assert.equal((await (await admin("check")).json()).sent, 0);
  assert.equal((await database.prepare("SELECT COUNT(*) AS total FROM sent_matches").first()).total, 1);
  acceptEmail = true;
  assert.equal((await (await admin("check")).json()).sent, 1);
  assert.equal((await database.prepare("SELECT COUNT(*) AS total FROM sent_matches").first()).total, 2);
  const saved = await preference("PUT", { ...original, paused: true });
  assert.equal(saved.status, 200);
  assert.equal((await preference("PUT", { ...original, paused: false })).status, 409);
  assert.equal((await (await preference()).json()).paused, true);
  assert.equal((await (await admin("check")).json()).sent, 0);
  assert.equal((await admin("enroll", { email: "owner@example.test" })).status, 200);
  assert.equal(messages.length, 3);
  await database.prepare("UPDATE access_tokens SET expires_at=0").run();
  assert.equal((await preference()).status, 401);
  const stored = await database.prepare("SELECT digest FROM access_tokens LIMIT 1").first();
  assert.notEqual(stored.digest, token);
  for (let attempt = 0; attempt < 4; attempt++) {
    const delivery = Promise.withResolvers();
    onDelivery = delivery.resolve;
    const recovery = await runtime.dispatchFetch("https://alerts.test/request-link", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: "owner@example.test" }) });
    assert.equal(recovery.status, 202);
    if (attempt < 3) await delivery.promise;
  }
  assert.equal(messages.length, 6);
  assert.match(messages.at(-1).body, /all paused/);
  assert.equal((await admin("enroll", { email: "public@example.test" })).status, 200);
  assert.doesNotMatch(messages.at(-1).body, /#token=/);
  const publicPreference = (method = "GET", body) => runtime.dispatchFetch("https://alerts.test/preferences", { method, headers: { Origin: "https://fbp26.github.io", "Content-Type": "application/json" }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const publicOriginal = await (await publicPreference()).json();
  assert.equal(publicOriginal.email, "public@example.test");
  assert.deepEqual(publicOriginal.courseGroups.map(group => group.value), ["group:all", "group:local", "group:regional"]);
  const publicSaved = await (await publicPreference("PUT", { ...publicOriginal, paused: true, rules: [{ ...publicOriginal.rules[0], course: "group:all" }] })).json();
  assert.equal(publicSaved.ok, true);
  assert.ok(publicSaved.savedAt > 0);
  assert.equal((await publicPreference("PUT", { ...publicOriginal, paused: false })).status, 409);
  const publicReloaded = await (await publicPreference()).json();
  assert.equal(publicReloaded.paused, true);
  assert.equal(publicReloaded.rules[0].course, "group:all");
  assert.equal(publicReloaded.savedAt, publicSaved.savedAt);
  assert.equal((await (await admin("check")).json()).sent, 0);
  assert.equal((await runtime.dispatchFetch("https://alerts.test/admin/check", { method: "POST" })).status, 401);
  assert.equal((await runtime.dispatchFetch("https://alerts.test/preferences", { method: "PUT", headers: { Origin: "https://evil.test" } })).status, 403);
  console.log("PASS: public single-mailbox editing, server save timestamps and stale-save protection; admin remains private.");
  console.log("PASS: D1 enrollment, welcome summary/link, matching delivery, failed-delivery retry, deduplication, preferences, version conflicts, pause, token hashing/expiry and rate-limited recovery. All email was mocked.");
} finally { await runtime.dispose(); }

const vapid = createECDH("prime256v1");
vapid.generateKeys();
const pushRuntime = createRuntime({ EMAIL_DELIVERY_ENABLED: "false", VAPID_PUBLIC_KEY: vapid.getPublicKey().toString("base64url"), VAPID_PRIVATE_KEY: vapid.getPrivateKey().toString("base64url") });
try {
  const database = await pushRuntime.getD1Database("DB");
  const schema = await readFile(new URL("schema.sql", import.meta.url), "utf8");
  for (const statement of schema.split(";").map(value => value.trim()).filter(Boolean)) await database.prepare(statement).run();
  await database.prepare("INSERT INTO subscribers (id, email, rules, created_at) VALUES (?, ?, ?, ?)").bind("push-owner", "public@example.test", JSON.stringify(defaultAlerts), Date.now()).run();
  const deviceKey = createECDH("prime256v1");
  deviceKey.generateKeys();
  const subscription = { endpoint: "https://web.push.apple.com/device-one", keys: { p256dh: deviceKey.getPublicKey().toString("base64url"), auth: randomBytes(16).toString("base64url") } };
  const pushAction = (action, value = subscription) => pushRuntime.dispatchFetch(`https://alerts.test/push/${action}`, { method: "POST", headers: { "Content-Type": "application/json", Origin: "https://fbp26.github.io" }, body: JSON.stringify({ subscription: value }) });
  const check = async () => (await pushRuntime.dispatchFetch("https://alerts.test/admin/check", { method: "POST", headers: { Authorization: "Bearer test-admin" } })).json();
  const mailCount = messages.length;
  assert.equal((await (await pushRuntime.dispatchFetch("https://alerts.test/push/config")).json()).configured, true);
  assert.equal((await pushAction("test")).status, 400);
  assert.equal((await pushAction("subscribe", { ...subscription, endpoint: "https://localhost/private" })).status, 400);
  assert.equal((await pushAction("subscribe")).status, 200);
  assert.equal((await pushAction("subscribe")).status, 200);
  assert.equal((await database.prepare("SELECT COUNT(*) AS total FROM push_devices").first()).total, 1);
  const testPush = await pushAction("test");
  assert.equal(testPush.status, 200, await testPush.text());
  assert.equal(pushes.length, 1);
  assert.equal((await check()).pushSent, 1);
  const snapshot = await database.prepare("SELECT id FROM push_results LIMIT 1").first();
  const savedMatches = await (await pushRuntime.dispatchFetch(`https://alerts.test/push/results/${snapshot.id}`)).json();
  assert.equal(savedMatches.notificationId, snapshot.id);
  assert.equal(savedMatches.teeTimes.length, 1);
  assert.equal(savedMatches.teeTimes[0].allInPrice, 118);
  assert.equal(savedMatches.teeTimes[0].course, "Spring Creek Golf Club");
  assert.equal((await check()).pushSent, 0);
  feed.teeTimes[0].allInPrice = 117;
  assert.equal((await (await pushRuntime.dispatchFetch(`https://alerts.test/push/results/${snapshot.id}`)).json()).teeTimes[0].allInPrice, 118);
  pushStatus = 503;
  assert.equal((await check()).pushFailed, 1);
  assert.equal((await database.prepare("SELECT COUNT(*) AS total FROM push_results").first()).total, 1);
  pushStatus = 201;
  assert.equal((await check()).pushSent, 1);
  await database.prepare("UPDATE subscribers SET paused=1").run();
  feed.teeTimes[0].allInPrice = 116;
  assert.equal((await check()).pushSent, 0);
  await database.prepare("UPDATE subscribers SET paused=0").run();
  pushStatus = 410;
  assert.equal((await check()).pushSent, 0);
  assert.equal((await database.prepare("SELECT COUNT(*) AS total FROM push_devices").first()).total, 0);
  assert.equal((await database.prepare("SELECT COUNT(*) AS total FROM push_matches").first()).total, 0);
  pushStatus = 201;
  assert.equal((await pushAction("subscribe")).status, 200);
  assert.equal((await pushAction("unsubscribe")).status, 200);
  assert.equal((await database.prepare("SELECT COUNT(*) AS total FROM push_devices").first()).total, 0);
  assert.equal((await pushRuntime.dispatchFetch("https://alerts.test/request-link", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: "public@example.test" }) })).status, 409);
  assert.equal(messages.length, mailCount);
  await database.prepare("UPDATE push_results SET expires_at=0").run();
  assert.equal((await pushRuntime.dispatchFetch(`https://alerts.test/push/results/${snapshot.id}`)).status, 400);
  console.log("PASS: Apple-compatible encrypted push, device registration/test/removal, deduplication, failure retry, pause, expired subscription cleanup, and ZERO email delivery in push-only mode. All push delivery was mocked.");
} finally { await pushRuntime.dispose(); }

const signupRuntime = createRuntime({ EMAIL_DELIVERY_ENABLED: "false", SIGNUP_EMAIL_TO: "owner-notices@example.test", VAPID_PUBLIC_KEY: vapid.getPublicKey().toString("base64url"), VAPID_PRIVATE_KEY: vapid.getPrivateKey().toString("base64url") });
try {
  const database = await signupRuntime.getD1Database("DB");
  const schema = await readFile(new URL("schema.sql", import.meta.url), "utf8");
  for (const statement of schema.split(";").map(value => value.trim()).filter(Boolean)) await database.prepare(statement).run();
  await database.prepare("INSERT INTO subscribers (id, email, rules, created_at) VALUES (?, ?, ?, ?)").bind("signup-owner", "public@example.test", JSON.stringify(defaultAlerts), Date.now()).run();
  const deviceKey = createECDH("prime256v1");
  deviceKey.generateKeys();
  const subscription = { endpoint: "https://web.push.apple.com/new-signup", keys: { p256dh: deviceKey.getPublicKey().toString("base64url"), auth: randomBytes(16).toString("base64url") } };
  const oldSubscription = { ...subscription, endpoint: "https://web.push.apple.com/existing-before-release" };
  await database.prepare("INSERT INTO push_devices (id, subscriber_id, endpoint, subscription, created_at) VALUES (?, ?, ?, ?, ?)").bind("existing-device", "signup-owner", oldSubscription.endpoint, JSON.stringify(oldSubscription), Date.now()).run();
  const action = (path, value = subscription) => signupRuntime.dispatchFetch(`https://alerts.test/push/${path}`, { method: "POST", headers: { "Content-Type": "application/json", "User-Agent": "iPhone", Origin: "https://fbp26.github.io" }, body: JSON.stringify({ subscription: value, email: "ignored@example.test" }) });
  const check = async () => (await signupRuntime.dispatchFetch("https://alerts.test/admin/check", { method: "POST", headers: { Authorization: "Bearer test-admin" } })).json();
  const mailCount = messages.length;
  assert.equal((await (await action("subscribe", oldSubscription)).json()).newDevice, false);
  assert.equal((await database.prepare("SELECT COUNT(*) AS total FROM signup_notifications").first()).total, 0);
  const delivery = Promise.withResolvers();
  onDelivery = delivery.resolve;
  const registrations = await Promise.all([action("subscribe"), action("subscribe")]);
  const results = await Promise.all(registrations.map(response => response.json()));
  assert.equal(results.filter(result => result.newDevice).length, 1);
  await delivery.promise;
  assert.equal(messages.length, mailCount + 1);
  assert.equal(messages.at(-1).to, "owner-notices@example.test");
  assert.match(messages.at(-1).subject, /notification signup/);
  assert.match(messages.at(-1).body, /iPhone/);
  assert.doesNotMatch(messages.at(-1).body, /new-signup|ignored@example.test/);
  assert.equal((await database.prepare("SELECT COUNT(*) AS total FROM signup_notifications").first()).total, 1);
  assert.equal((await action("unsubscribe")).status, 200);
  assert.equal((await (await action("subscribe")).json()).newDevice, false);
  await database.prepare("INSERT INTO signup_notifications (id, device_kind, created_at) VALUES (?, ?, ?)").bind("retry-test", "Browser device", Date.now()).run();
  acceptEmail = false;
  await check();
  const failed = await database.prepare("SELECT * FROM signup_notifications WHERE id='retry-test'").first();
  assert.equal(failed.sent_at, null);
  assert.equal(failed.attempts, 1);
  assert.match(failed.last_error, /not accepted/);
  acceptEmail = true;
  await database.prepare("UPDATE signup_notifications SET claim_until=0 WHERE id='retry-test'").run();
  await check();
  assert.ok((await database.prepare("SELECT sent_at FROM signup_notifications WHERE id='retry-test'").first()).sent_at);
  const deliveredCount = messages.length;
  await check();
  assert.equal(messages.length, deliveredCount);
  assert.equal(messages.length, mailCount + 2);
  assert.ok(messages.slice(mailCount).every(message => message.to === "owner-notices@example.test" && message.subject === "New Golf With Jim notification signup"));
  console.log("PASS: future-only owner signup emails, atomic concurrent-registration deduplication, refresh/re-enable suppression, durable failure retry, fixed recipient and no tee-time email delivery. All mail was mocked.");
} finally { await signupRuntime.dispose(); }